### ISSUE TITLE
Error in templates.yaml

### ISSUE THREAD

**Issue by phoenix-blue** [bertreb/plafonds#1]
Hello,

I hav follow the guidline, but get an error in the templates.yaml.
Before this problem, i have change the python name to plafond.py in place of plafonds.py because some errors in the automation script.

But the templates,yaml, i have insert this part from the readme:

```
- sensor:
  - name: gasplafond dag
    unit_of_measurement: "m³"
    icon: "mdi:fire"
    device_class: gas
    state: >
      {% if states('sensor.gasplafond_dag')|float(0) > 0 %}
        {{ '{:.2f}'.format(states('sensor.gasplafond_dag')|float(0)) }}
      {% endif %}
```

But stil haveing this error:

```
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:518
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 19:00:20 (4 occurrences)
Last logged: 19:04:08

The system cannot restart because the configuration is not valid: Invalid config for [sensor]: required key not provided @ data['platform']. Got None. (See ?, line ?).
The system cannot restart because the configuration is not valid: Error loading /config/configuration.yaml: in "/config/configuration.yaml", line 85, column 11: Unable to read file /config/templates.yaml.
```

how can i solve this part?

**Comment by bertreb** [comment]
Did you add/use in configuration.yaml?
```
template: !include template.yaml
```
If you created templates.yaml (with a S) the include should also be to the same filename in configuration.yaml. 
So in your case:
```
template: !include templates.yaml
```

**Comment by bertreb** [comment]
Secondly
If you changed the name of the python script to plafond.py, you also need to change the name in services.yaml. 
```
plafonds:     -> plafond:
```

**Comment by phoenix-blue** [comment]
Hello,

Thanks for the quick response.
I have change the services.yaml and I had already included the templates.yaml.

But when I want to reboot/restart HA from this part I get an [object] error.
So I think something has to do it with the templates.yaml

**Comment by phoenix-blue** [comment]
Think found the problem 
different between an file name template.yaml and templates.yaml ;-)
